spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456a-
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 43327956296-k8d9l5t2d1epjba7ajhf1nqcrka9k545.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example.travelblog.model