spring.application.name=shahara

spring.datasource.url=jdbc:mysql://localhost:3306/shahara
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456a-

#Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhat.tranvanminh@gmail.com
spring.mail.password=prtziumspvdqzeye
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
